CREATE TABLE PERSON(
    NO NUMBER(10) PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20)
);

CREATE SEQUENCE PERSON_SEQ
START WITH 1 
INCREMENT BY 1 
MAXVALUE 9999999999;